version: '3.8'
services:
  web:
    image: php:8.2-apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    command: >
      bash -c "docker-php-ext-install pdo pdo_mysql && apache2-foreground"

  db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: asix
    volumes:
      - ./sql/botiga.sql:/docker-entrypoint-initdb.d/botiga.sql
    ports:
      - "3306:3306"
